# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: P:/Adder/two_bit_adder/Nexys4DDR_Master.xdc

# Block Designs: bd/Adderblock_design/Adderblock_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adderblock_design || ORIG_REF_NAME==Adderblock_design} -quiet] -quiet

# IP: bd/Adderblock_design/ip/Adderblock_design_half_adder_0_0/Adderblock_design_half_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adderblock_design_half_adder_0_0 || ORIG_REF_NAME==Adderblock_design_half_adder_0_0} -quiet] -quiet

# IP: bd/Adderblock_design/ip/Adderblock_design_full_adder_0_0/Adderblock_design_full_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adderblock_design_full_adder_0_0 || ORIG_REF_NAME==Adderblock_design_full_adder_0_0} -quiet] -quiet

# XDC: bd/Adderblock_design/Adderblock_design_ooc.xdc
